name: CI

# 在 main 分支发生 push 事件时触发
on: 
  push:
    branches:
      - main

jobs: # 工作流
  build:
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps: 
      - name: Checkout # 步骤1
        uses: actions/checkout@v2 # 使用的动作。作用：检出仓库，获取源码。官方actions库：https://github.com/actions
      - name: Install Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v2 # 作用：安装 Nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - name: Build and Deploy # 步骤3
        env: # 设置环境变量【在仓库的 secret 中配置 ACCESS_TOKEN 变量】
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # GitHub access token 私密变量
        run: npm install && npm run deploy # 执行的命令  
        # package.json 中添加 "deploy": "bash deploy.sh"
